#!/usr/bin/env python

import argparse
import os
import subprocess
import sys
from collections import defaultdict
from os import path


def isint(thing):
    try:
        int(thing)
    except ValueError:
        return False
    else:
        return True


here = path.dirname(__file__)
days = set()
day_parts = defaultdict(set)

with os.scandir(path.join(here, "days")) as it:
    for entry in it:
        if not entry.is_dir() or not isint(entry.name):
            continue
        days.add(int(entry.name))

for day in days:
    with os.scandir(path.join(here, "days", str(day))) as it:
        for entry in it:
            if not entry.is_file():
                continue
            name, ext = path.splitext(entry.name)
            if not isint(name) or ext != ".py":
                continue
            day_parts[day].add(int(name))

argparser = argparse.ArgumentParser()
group = argparser.add_argument_group()
argparser.add_argument(
    "-d",
    "--day",
    type=int,
    default=None,
    choices=list(days),
    metavar="N",
    help="Which day's solutions to run. Omit to run all.",
)
argparser.add_argument(
    "-p",
    "--part",
    type=int,
    default=None,
    choices=[1, 2],
    metavar="N",
    help="Which part of the day's solutions to run. Omit to run all.",
)
argparser.add_argument(
    "-t",
    "--test",
    default=False,
    help="Run the tests for the selected days and parts.",
    action="store_true",
)
argparser.add_argument(
    "--pypy",
    default=False,
    help="Run the solution using pypy",
    action="store_true",
)
args = argparser.parse_args()

if args.day is not None and args.part is not None:
    solutions = [(args.day, args.part)]
else:
    solutions = [
        (day, part)
        for day in sorted(days or [args.day])
        for part in (sorted(day_parts[day]) if args.part is None else [args.part])
    ]


if args.test:
    import pytest

    pytest.main(
        [
            path.join(here, "days", str(day), f"test_{part}{os.extsep}py")
            for day, part in solutions
        ]
    )
else:
    start = True
    for day, part in solutions:
        if start:
            start = False
        else:
            print()
        print(f"Day {day} part {part}:\n")
        try:
            subprocess.run(
                [
                    "pypy" if args.pypy else "python",
                    path.join(here, "days", str(day), f"{part}{os.extsep}py"),
                ],
                check=True,
            )
        except subprocess.CalledProcessError:
            print(f"Day {day} part {part} failed", file=sys.stdout)
